# 第一章 numpy常用操作

##  第一节：生成ndarray的几种方式

## 1.从已有数据创建

In [1]:
import numpy as np   #导入numpy
list1=[1,2,3,4,6,8,5,9,11,45,1.25,0.254]
nd1=np.array(list1) #创建ndarray
print(nd1)
print(type(nd1))

[ 1.     2.     3.     4.     6.     8.     5.     9.    11.    45.
  1.25   0.254]
<class 'numpy.ndarray'>


In [1]:
## 2 嵌套列表可以转换多维ndarray 

In [2]:
import numpy as np
list2=[[1.0,2,3,5,7,9],[2,4],[6,8,10]]
nd2=np.array(list2)
print(nd2)
print(type(nd2))

[list([1.0, 2, 3, 5, 7, 9]) list([2, 4]) list([6, 8, 10])]
<class 'numpy.ndarray'>


# 第二节 利用random模块生成ndarray
## random有多种函数分别为：

## random : 生成0 - 1之间的随机矩阵

## uniform : 生成均匀分布随机数

## randn   ：根据给定维度生成一个或一组样本，具有标准正态分布

## rand      : 根据给定维度生成0-1之间的数据，包含0不包含1

## normal  : 生成正态分布

## shuffle  : 随机 打乱顺序

## seed      : 设置随机数种子

In [3]:
# import numpy as np
nd5= np.random.random([3,3])  #生成0-1之间的随机数
print('随机数：\n',nd5)
print(type(nd5))
nd6=np.random.uniform([1,3])
print('均匀分布随机数：\n',nd6)
nd7=np.random.randn(5,5)
print('标准正态随机数：\n',nd7)



随机数：
 [[0.3927166  0.80205797 0.85009778]
 [0.54327433 0.96391778 0.20146652]
 [0.93898333 0.34405539 0.12503133]]
<class 'numpy.ndarray'>
均匀分布随机数：
 [1.         1.09631829]
标准正态随机数：
 [[-0.35720696  0.95111815 -0.80764804  0.53589443  1.34880793]
 [ 1.46960957 -0.5437662  -0.06836763  0.68085097  0.60391466]
 [-0.61105729  1.39444318  1.6790768   0.39328295  1.02038385]
 [-0.13989587  0.67327485 -0.56000817  0.61108164 -0.26179102]
 [ 0.46821335  0.18704824  1.05835508 -1.87400868  0.8231638 ]]
